version: 2.1
workflows:
  build-deploy:
    jobs:
      - test-orb-locally
      - publish:
          requires:
            - test-orb-locally
          filters:
            branches:
              only: master

jobs:
  test-orb-locally:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - run:
          name: Pack and Validate
          command: |
            

            repo_prefix="devops-circleci-orb-";
            ORB_NAME=${${CIRCLE_PROJECT_REPONAME}#$prefix}; 
            circleci config pack src/ > packed.yml
            circleci orb validate packed.yml --token ${CIRCLE_API_KEY}
            if circleci orb publish packed.yml lbh-test/${CIRCLE_JOB}@dev:${CIRCLE_BRANCH} --token ${CIRCLE_API_KEY}; then
              echo Existing Orb updated
            else
              circleci orb create lbh-test/${ORB_NAME} --no-prompt --token ${CIRCLE_API_KEY}
              circleci orb publish packed.yml lbh-test/${ORB_NAME}@dev:${CIRCLE_BRANCH} --token ${CIRCLE_API_KEY}
              echo New Orb published
            fi
  publish:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - run:
          name: Promote to prod
          command: |
            circleci orb publish promote lbh-test/${ORB_NAME}@dev:${CIRCLE_BRANCH} patch --token ${CIRCLE_API_KEY}
