version: 2.1
workflows:
  build-deploy:
    jobs:
      - test-orb-locally
      - publish:
          requires:
            - test-orb-locally
          filters:
            branches:
              only: master

jobs:
  test-orb-locally:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - run:
          name: Pack and Validate
          command: |
            circleci config pack src/ > packed.yml
            ls -la
            circleci orb validate packed.yml --token ${CIRCLECI_API_KEY}
            circleci orb publish packed.yml lbh-test/${CIRCLE_JOB}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1} --token ${CIRCLECI_API_KEY}
  publish:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - run:
          name: Promote to prod
          command: |
            circleci orb publish promote lbh-test/${CIRCLE_JOB}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1} patch --token ${CIRCLECI_API_KEY}
