version: 2.1
workflows:
  build-deploy:
    jobs:
      - test-orb-locally
      - publish:
#           requires:
#             - test-orb-locally
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/

jobs:
  test-orb-locally:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - run:
          name: Pack and Validate
          command: |
            circleci config pack src/ > packed.yml
            circleci orb validate packed.yml --token ${CIRCLE_API_KEY}
            if circleci orb publish packed.yml lbh-test/test-mvp@dev:${CIRCLE_BRANCH} --token ${CIRCLE_API_KEY}; then
              echo Existing Orb updated
            else
              circleci orb create lbh-test/${ORB_NAME} --no-prompt --token ${CIRCLE_API_KEY}
              circleci orb publish packed.yml lbh-test/test-mvp@dev:${CIRCLE_BRANCH} --token ${CIRCLE_API_KEY}
              echo New Orb published
            fi
  publish:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - run:
          name: Configure Environment
          command: |
            export CURRENT_VERSION=eval `circleci orb info lbh-test/test-mvp@volatile | grep -oE '(\d+\.)+\d+\b'`
            echo "export NEXT_VERSION=`echo $CIRCLE_TAG | grep -oE '(\d+\.)+\d+\b'`" >> $BASH_ENV
            env
      - run:
          name: Promote to prod
          command: |
            env
            echo current: ${CURRENT_VERSION} next: ${NEXT_VERSION}
            circleci orb publish promote lbh-test/test-mvp@dev:${CIRCLE_BRANCH} patch --token ${CIRCLE_API_KEY}
