version: 2.1

orbs:
  helloOrb:
    commands:
      my_command:
        parameters:
          some_word:
            type: string
        steps:
          - run: echo "<<parameters.some_word>> World"  
    jobs:
      my_build:
        docker:
          - image: circleci/circleci-cli
        steps:
          - checkout
          - run: circleci help
          - my_command:
              some_word: Hi
            

workflows:
  hello-workflow:
    jobs:
      - helloOrb/my_build
