version: 2.1
commands:
  my_command:
    parameters:
      some_word:
        type: string
    steps:
      - run: echo "<<parameters.some_word>> World"
  command_snd:
    #parameters: simple case
    steps:
      - run: | #I could just run the script, or...
          echo "Whatever"
          #>>Script1|./shell/my_test_script.sh<<#

jobs:
  my_build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - my_command:
          some_word: "Hello from GitHub"
